# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# asdf
. $(brew --prefix asdf)/libexec/asdf.sh

export EDITOR=nano

export GPG_TTY=$(tty)

alias ga="git add -A ."
alias branch="git branch -av"
alias be="bundle exec"
alias rs="bundle exec rails server"
alias rc="bundle exec rails console"
alias ber="be rake"
alias r="be rspec"
alias yr="yarn run"

# Rubygems/Bundler configuration
export GEM_EDITOR=subl
export BUNDLER_EDITOR=subl

# Git prompt configuration
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWCOLORHINTS=true
source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh

# Homebrew completion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Shell configuration

precmd () {
  # Terminal.app cwd notification
  printf '\e]7;%s\a' "file://$HOST$PWD"

  # Git prompt injection
  __git_ps1 "%~" "$ " " (%s)"
}

# completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

autoload -U select-word-style
select-word-style bash

# history
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=10000
setopt extended_history # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt inc_append_history # add commands to HISTFILE at execution rather than upon shell exit
setopt share_history # share command history data between shells

source ~/.profile
