# rbenv
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"

# nodenv
export NODENV_ROOT=/usr/local/var/nodenv
eval "$(nodenv init -)"

export EDITOR=nano

export GPG_TTY=$(tty)

alias ga="git add -A ."
alias branch="git branch -av"
alias be="bundle exec"
alias rs="rails server"
alias rc="rails console"
alias ber="be rake"
alias r="be rspec"

function yarnx {
  `yarn bin`/$1 "${@:2}"
}

# Git prompt configuration
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWCOLORHINTS=true
source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh

# Homebrew completion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Shell configuration

precmd () {
  # Terminal.app cwd notification
  printf '\e]7;%s\a' "file://$HOST$PWD"

  # Git prompt injection
  __git_ps1 "%~" "$ " " (%s)"
}

# completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

autoload -U select-word-style
select-word-style bash

source ~/.profile
