export EDITOR=nano
export PATH="$PATH:`yarn global bin`"

alias ga="git add -A ."
alias branch="git branch -av"
alias be="bundle exec"
alias rs="rails server"
alias rc="rails console"
alias ber="be rake"
alias r="be rspec"

# Homebrew bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Git prompt injection
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWCOLORHINTS=true
PROMPT_COMMAND='update_terminal_cwd; __git_ps1 "\h:\w" "\\\$ "'

# rbenv
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"

source ~/.profile
