export EDITOR=nano

alias dl="less -Rfn +F log/development.log"
alias ga="git add -A ."
alias glg="git lg"
alias branch="git branch -av"
alias be="bundle exec"
alias rs="rails server"
alias rc="rails console"
alias ss="script/server"
alias sc="script/console"
alias ur="unicorn_rails --listen 3000"
alias ber="be rake"
alias r="be rspec"
alias g="be guard"
alias dbreset="ber db:drop db:create db:migrate db:seed db:test:clone"

function push {
  BRANCH=`git branch | grep '^*' | colrm 1 2`
  git push origin $BRANCH
}

function pushf {
  BRANCH=`git branch | grep '^*' | colrm 1 2`
  git push -f origin $BRANCH
}

# Git tab-completion and prompt injection
source /usr/share/git-core/git-completion.bash
source /usr/share/git-core/git-prompt.sh
export PS1="\h:\w\[\033[0;32m\]\$(__git_ps1)\[\033[00m\]\$ "

# rbenv
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"

source ~/.profile
