export EDITOR=nano

alias dl="less -Rfn +F log/development.log"
alias ga="git add -A ."
alias glg="git lg"
alias branch="git branch -av"
alias be="bundle exec"
alias rs="rails server"
alias rc="rails console"
alias ss="script/server"
alias sc="script/console"
alias ur="unicorn_rails --listen 3000"
alias ber="be rake"
alias r="be rspec"
alias c="be cucumber"
alias g="be guard --notify false"

function push {
  BRANCH=`git branch | grep '^*' | colrm 1 2`
  git push origin $BRANCH
}

function pushf {
  BRANCH=`git branch | grep '^*' | colrm 1 2`
  git push -f origin $BRANCH
}

# Git tab-completion and prompt injection
source /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWCOLORHINTS=true
PROMPT_COMMAND='update_terminal_cwd; __git_ps1 "\h:\w" "\\\$ "'

# Homebrew tab-completion
source `brew --repository`/Library/Contributions/brew_bash_completion.sh

# rbenv
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"

source ~/.profile
